version: "3.8"

services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  django:
    build: ./docker_project
    container_name: django_backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static  # Mount static files
      - media_volume:/app/media  # Mount media files
    networks:
      - mynetwork

  flask:
    build: ./flask_app
    container_name: flask_backend
    depends_on:
      - django
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  nginx:
    image: nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static  # Serve static files
      - media_volume:/app/media  # Serve media files
    depends_on:
      - django
      - flask
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:
  static_volume:
  media_volume:
